services:
  backend:
    image: golang:latest
    container_name: backend
    tty: true
    ports:
      - 8080:8080
    command: go run main.go
    volumes:
      - ./:/go/CharisWorks-BackEnd
  db:
    image: mariadb:latest
    container_name: db
    tty: true
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./sql_init:/docker-entrypoint-initdb.d
      - data-volume:/var/lib/mysql
  cli:
    image: stripe/stripe-cli:latest
    container_name: stripe_worker
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_DEVICE_NAME: ${STRIPE_DEVICE_NAME}
    command: stripe listen --forward-to localhost:8080/stripe_webhooks
volumes:
  data-volume:
