export STRIPE_API_KEY=sk_test_51Nj1urA3bJzqElthx8UK5v9CdaucJOZj3FwkOHZ8KjDt25IAvplosSab4uybQOyE2Ne6xxxI4Rnh8pWEbYUwPoPG00wvseAHzl
export STRIPE_DEVICE_NAME=dev
export FIREBASE_AUTH_EMULATOR_HOST=localhost:9091
export CHARIS_PROJECT_ENV=dev
cd test_server
docker compose up