services:
  db:
    image: mariadb:latest
    container_name: mock_db
    tty: true
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      # この行がないと起動しない
      MYSQL_DATABASE: CharisWorks
      TZ: "Asia/Tokyo"
    volumes:
      - ./sql_init:/docker-entrypoint-initdb.d
  stripe-cli:
    image: stripe/stripe-cli
    container_name: test_stripe_cli
    tty: true
    ports:
      - 4242:4242
    environment:
      STRIPE_API_KEY: sk_test
volumes:
  data-volume:
